const actionType ={
    ADD_APOIO:'ADD_APOIO',
    REMOVER_APOIO:'REMOVER_APOIO',
    ADD_CAR:'ADD_CARR',
    REMOVER_CAR:'REMOVER_CAR',
    MODIFICAR_COMPRIMENTO:'MODIFICAR_COMPRIMENTO',
    ADD_COMB:"ADD_COMB",
    ADD_CARACTERISTICAS:"ADD_CARACTERISTICAS",
    ADD_INF:"ADD_INF",
    COMB:"COMB  S",
    COMB_LOGICO:'COMB_LOGICO',
    SALVAR:'SALVAR'

}

export default actionType